# Generated by Django 5.1.2 on 2025-07-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resumate', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
