# Generated by Django 5.1.2 on 2025-07-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resumate', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
